### ISSUE TITLE
Couldn't fix the about page & getting start...

### ISSUE THREAD

**Issue by wanyt** [jekyller/jasper2#39]
#36 I met the same problem, and tried all the solution, but it also doesn't work. Who can help me?
[https://github.com/wanyt/wanyt.github.io/blob/master/_config.yml#L18:3](url)

**Comment by kmcconnell** [comment]
Your config.yml looks like it was copied from my site instead of using the original config.yml from https://github.com/jekyller/jasper2. I've customized my site a bit, so copying from there won't help much if you're starting from scratch with jekyller/jasper2.

**Comment by wanyt** [comment]
Think you! @kmcconnell Now I using the original config.yml, [https://github.com/wanyt/wanyt.github.io/blob/master/_config.yml](url), but the about page still doesn't work.

**Comment by kmcconnell** [comment]
If you look at those pages, you'll see they're "working" but the CSS files aren't loading. The links in the head are just `assets/build/screen.css` instead of `/assets/build/screen.css` which I think is what's causing that issue. I think that liquid variable should be rendering there so the link renders as `/assets/build/screen.css`.

That depends on how you're building the site I suppose. Are you just using `bundle exec jekyll build`?

**Comment by wanyt** [comment]
Yeah! I run this command `bundle exec jekyll build`locally, then using `bundle exec jekyll build` preview the website, Finally, I push the code to Github repository. Is there any other operation?

**Comment by biomadeira** [comment]
Thanks @kmcconnell  for your help!

F:)

**Comment by kmcconnell** [comment]
@biomadeira no worries.

@wanyt I'm not entirely clear as to how you've set up your site on GitHub. When I clone your master branch at the latest commit and run `bundle exec jekyll build`, the site is generated into the `_site` folder and everything looks correctly generated. If I run `bundle exec jekyll serve` the site previews perfectly.

I see that you also have a gh-pages branch, and those URLs look correct as well to me. In both cases, I see the following in the head.

```html
<!-- Styles'n'Scripts -->
<link rel="stylesheet" type="text/css" href="/assets/built/screen.css" />
<link rel="stylesheet" type="text/css" href="/assets/built/screen.edited.css" />
```

However, if I view the source as published on https://wanyt.github.io, I'm still seeing that the leading / is missing.

```html
<!-- Styles'n'Scripts -->
<link rel="stylesheet" type="text/css" href="assets/built/screen.css" />
<link rel="stylesheet" type="text/css" href="assets/built/screen.edited.css" />
```

To me, the issue doesn't seem to be in the repo, but maybe in the way GitHub builds the site differently than Jekyll on your local machine. I don't deploy to GitHub Pages so I'm not familiar with what that difference might be. But I can say that the static resources rendered in the _site folder are rendering correctly. Hopefully someone else might be able to offer a tip on what the difference might be.

**Comment by Wei-Xia** [comment]
@kmcconnell @wanyt  Not sure if you have figured out, but I ran into the same issue like you.

Even though the styling looks good like below,
```
<!-- Styles'n'Scripts -->
<link rel="stylesheet" type="text/css" href="assets/built/screen.css" />
<link rel="stylesheet" type="text/css" href="assets/built/screen.edited.css" />
```
But I guess this repo GitHub Pages is not coming from `wanyt.github.io` directly, it might build base on a repo like `wanyt.github.io/repoName`, and css url should be `/repoName/assets/built/screen.css`.

That's why even though code looks good, but style doesn't apply to the website.

Not sure if you catch what I'm meaning, but you can change those url from `baseurl` in `config.yml`.

Hope it could help you!

**Comment by jodeio** [comment]
@Wei-Xia, sadly having /repoName/assets/../ will surely make your static website require a project level github page url. (ex. username.github.io/required-repo-name). Will look into consideration why is the behaviour of '/' as base url is different when uploaded in gh pages.
