### ISSUE TITLE
missing html contant

### ISSUE THREAD

**Issue by bd3r** [jekyller/jasper2#51]
hello,
i was able to deploy the site correctly using travic :+1:
https://bd3r.github.io/jasper2/

but i would love to be able to use https://netlify.com
but the site after sucssful deployment looks broken and missing contant:
https://eager-borg-fd8d02.netlify.com/

deploy settings:

> Repository
>     https://github.com/bd3r/jasper2
> Build command
>     jekyll build
> 
> Publish directory
>     jasper2-pages/
> 
> Production branch
>     master
> 
> Branch deploys
>     Deploy only the production branch and its deploy previews
> 
> Public deploy logs
>     Logs are public

can you please help poining me in the right direction to fix this?
i have uploaded the html contant to the master branch on my repo under [jasper2-pages/](https://github.com/bd3r/jasper2/tree/master/jasper2-pages)
but that changed nothing

**Comment by diomed** [comment]
I didn't host anything on netlify yet, but what I can tell you from my experience of downloading this template for personal use is that you should try removing `/jasper2/` from every instance

so that in the end every link to file looks like this:
```
<link rel="stylesheet" type="text/css" href="assets/built/screen.css" />
<link rel="stylesheet" type="text/css" href="assets/built/screen.edited.css" />
```
maybe that'll help you as well

**Comment by xandr00** [comment]
@diomed I figured it out. Open your "_config.yml". Edit line #9 which should be "baseurl: /". Erase the "/" so that it reads "baseurl: ". Run "bundle exec jekyll serve" and then you'll see the website-pages. You should be able to open up the index.html in your browser now and it should be fine.

![2018-06-21_16-32-39](https://user-images.githubusercontent.com/443960/41746774-32912e24-7571-11e8-8ead-fbd0b1575c19.png)

**Comment by cmeeren** [comment]
For the record, I had trouble with an empty base URL (author/tag pages didn't work) and had to use `baseUrl: /`
